name: Upload Release Asset

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the target release version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - uses: mislav/bump-homebrew-formula-action@v3
      with:
        formula-name: psvadm
        formula-path: Formula/pvsadm.rb
        homebrew-tap: carmal891/homebrew-pvsadm
        base-branch: automate-bump-version-formulae
        download-url: https://github.com/ppc64le-cloud/pvsadm/releases/download/${{ steps.get_version.outputs.VERSION }}/pvsadm-darwin-amd64.tar.gz
        commit-message: |
            {{formulaName}} ${{ steps.get_version.outputs.VERSION }}
            Created by psvadm 
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





   #https://github.com/ppc64le-cloud/pvsadm/releases/download/v0.1.17/pvsadm-darwin-amd64.tar.gz
   #/repos/ppc64le-cloud/pvsadm/releases/tags/refs%2Ftags%2Fv0.1.17

   #https://github.com/ppc64le-cloud/pvsadm/releases/download/refs/tags/v0.1.17/pvsadm-darwin-amd64.tar.gz





