name: Upload Release Asset

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the target release version
      id: get_version
      run: echo "VERSION::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - run: go version

    - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: psvadm
          formula-path: Formula/pvsadm.rb
          homebrew-tap: https://github.com/carmal891/homebrew-pvsadm
          base-branch: automate-bump-version-formulae
          download-url: https://github.com/ppc64le-cloud/pvsadm/releases/download/v${{env.version}}/pvsadm-darwin-amd64.tar.gz
          commit-message: |
            {{formulaName}} v{{env.Version}}

            Created by psvadm 
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





   